### ISSUE TITLE
Suggestion: A way to increase/decrease the volume of the sounds

### ISSUE THREAD

**Issue by Icelight123** [petertalbanese/SoundSwapper#10]
Hello, I have tried this pluggin and it works fantasticlly but the sound level of the file doesnt change in game when I manually modify the file to be quieter. Is this something that could be added potentially?

**Comment by petertalbanese** [comment]
Hey there! I recall seeing adjustable volume in another plugin so I believe it can be added in!

We're currently working on a bunch of general improvements to the plugin like sound whitelist/blacklist and a debug overlay to see sound IDs without the need for other plugins. I'll see if I can get the volume adjustment in with these changes, otherwise I'll look into it after we get these done.

**Comment by Icelight123** [comment]
Thank you for the reply, looking forward to all the changes thank you!

**Comment by petertalbanese** [comment]
Added!

**Comment by Icelight123** [comment]
> Added!

Thank you so much ,amazing!
