### ISSUE TITLE
Add a global block list and include Leviathan specific sounds

### ISSUE THREAD

**Issue by gord5500** [petertalbanese/SoundSwapper#15]
This is getting abused by some players to help them with knowing what prayer to use on the awakened boss

https://clips.twitch.tv/FlirtyBadSnoodCharlietheUnicorn-_FJfrxyvjM-FMS3h

The sound ids are 7040, 7041, 7030.

Happy to make the code changes

**Comment by petertalbanese** [comment]
I can toss this change in tonight if needed, though I don't think this is against any game rules technically. Let me check with the RL folks!

People will always find a way to abuse things 😞

**Comment by gord5500** [comment]
I much appreciate you taking the time to look into it even if you end up not implementing this. Thank you very much

**Comment by petertalbanese** [comment]
Based on the recent news with Visual Sounds plugin, there is a very high chance this one catches the ban hammer as well. I'm going to see if we can work on a list of global locked sounds with RL and Jagex (albeit, we don't have good direct channels to Jagex). Until that is made, they will likely require us to shut down the plugin :( will keep you posted

**Comment by petertalbanese** [comment]
Seems like we got the OK from Jagex for now... We're still considering adding in something like area locks so that the plugin is disabled in certain regions, but haven't decided on a final solution yet. We don't want to do something like, say, disabling it for all instances or bosses. Would put a damper on a lot of PvM shenanigans. Waiting to get more official confirmation before we go making larger changes.

**Comment by gord5500** [comment]
Totally makes sense and would hate to see the plugin get taken down because of a few bad apples. Thanks very much for looking into it and your replies
