### ISSUE TITLE
Swapping sound effects with a custom sound mutes sound effect in question

### ISSUE THREAD

**Issue by vodicy** [petertalbanese/SoundSwapper#21]
I'm trying to custom swap a soundwith a short wav file I made just to try the plugin out. I've identified the sound effect I want to swap in game with the "debug sound effects" feature, typed the sound effect ID into the Custom Sounds field, pasted the wav file with the same sound ID number as the sound I'm wanting to swap into the SoundSwapper folder in my .runelite folder, and checked the box called "Swap Sound Effects". This results in no sound playing when the sound effect should happen. I've listened back to the wav file alone to make sure it has audible sound in it (which it does), tried using a different wav file, tried closing and reopening runelite, and I've tried using different sound IDs and matching the wav file name to the ID and preforming the action in game that should produce that sound. None of these troubleshoots worked and will still result in silence. Once the box called "Swap Sound Effects" has been un-checked, the vanilla in-game sound is able to play again but I'd like this plugin to work for me and others who might have the same problem.

**Comment by petertalbanese** [comment]
Hey! Sorry to hear that you're having issues.

It sounds like you have everything set up correctly. I'm testing it right now with Runelite up to date with the latest and not having issues on my end. This is on a Windows PC. Are you possibly on Mac/Linux? I haven't personally tested on other platforms.

As for how I'm testing - I put some .wav files in the SoundSwapper folder in my .runelite folder like you said 
![image](https://github.com/petertalbanese/SoundSwapper/assets/47373764/73ecfdc6-e186-4ee0-954e-c6007e6e5bca)

I chose 62 and 4025 since these are easy to test (close/open door and interface sound [e.g. click on different tabs in your bank]). Plugin settings look like the following:
![image](https://github.com/petertalbanese/SoundSwapper/assets/47373764/ef890cc8-882f-4397-a9ef-d508d739f26e)

Is your Blacklist empty as well? Typically, if you aren't getting any sound but the in-game sound is getting consumed, it means that you either have the sound blacklisted or the plugin is failing to find/load your sound file. I've also seen people accidentally give their file a double extension - e.g. they named the file 62.wav when Windows already knows it's a .wav file, so the file ends up named 62.wav.wav under the hood.

**Comment by vodicy** [comment]
Hi thanks for the speedy reply! I am on a PC. My blacklist is empty on the plugin. I've tried naming the wav file with just the sound ID number, and also tried naming it "number".wav. When i add the ".wav" extension in the file name it definitely doesn't work because it just plays the vanilla in-game sound, but when I leave ".wav" out of the file name and simply name it the ID number of the sound effect, this is when the sound is muted/doesn't play entirely. 

I looked into my .runelite folder and found a folder called "logs". I scrolled all the way down to the bottom of the most recent file called "client" and found a line of text saying "2024-05-15 23:43:01 EDT [Client] WARN  com.soundswapper.SoundSwapperPlugin - Failed to play custom sound"

I asked my friend to troubleshoot with me and he has had the same problem as I've experienced with the plugin, and he was actually the one who pointed out the log folder. We also noticed that with the Debug Sound Effects option turned on, we can see that when attempting to trigger the sound which we're trying to swap the debug panel reads the sound effect as "Custom" in a light pink colour

**Comment by vodicy** [comment]
For clarity the sound ID im using to test is 2244, which i believe is to equip a ranged weapon to wear, so I'm naming my wave file "2244" and typing 2244 into the Custom Sounds field).

**Comment by petertalbanese** [comment]
Could you send me the sound file you're testing with by chance? I can share one that is working from my setup as well. Github only allows you to send images in these comments so I'd recommend hoping in the Discord (https://discord.gg/F2mfSvcnaj) and we can help you debug further there. Check out #support channel.

Also another thought - where did you get the .wav file from? If you converted it from .mp3 or some other source, did you use an online converter?

**Comment by vodicy** [comment]
Thanks, I'll follow up on discord in just a bit!

**Comment by petertalbanese** [comment]
Narrowed down to an issue with the file - vodicy was able to get it working after tweaking settings in their audio program!

Only noteable difference I see is the bitrate of the files. Will update this thread if I find anything, but closing for now.
